export const APP_ROLES = [
  'ADMIN', 'HOUSING_MANAGER', 'HOUSING_STAFF', 'TECHNICAL_MANAGER', 'TECHNICIAN',
  'HOUSEKEEPING', 'WAREHOUSE_MANAGER', 'HR_MANAGER', 'SECURITY', 'STAFF',
] as const;

export type AppRole = typeof APP_ROLES[number];

export const ROLE_LABELS: Record<AppRole, string> = {
  ADMIN: 'Sistem Yöneticisi', HOUSING_MANAGER: 'Lojman Müdürü', HOUSING_STAFF: 'Lojman Çalışanı',
  TECHNICAL_MANAGER: 'Teknik Müdür', TECHNICIAN: 'Teknik Çalışan', HOUSEKEEPING: 'Kat Hizmetleri Personeli',
  WAREHOUSE_MANAGER: 'Depo Sorumlusu', HR_MANAGER: 'İnsan Kaynakları Yetkilisi',
  SECURITY: 'Güvenlik Personeli', STAFF: 'Personel Portal Kullanıcısı',
};

export type UiPermission =
  | 'DASHBOARD_VIEW' | 'EMPLOYEE_VIEW' | 'EMPLOYEE_SENSITIVE_VIEW' | 'EMPLOYEE_MANAGE'
  | 'ROOM_VIEW' | 'ROOM_MANAGE' | 'ROOM_INVENTORY_MANAGE' | 'CLEANING_MANAGE' | 'MAINTENANCE_VIEW' | 'MAINTENANCE_CREATE'
  | 'MAINTENANCE_UPDATE' | 'MAINTENANCE_FULL_UPDATE' | 'MAINTENANCE_EXPORT' | 'VISITOR_VIEW'
  | 'VISITOR_MANAGE' | 'VISITOR_ARCHIVE' | 'STOCK_VIEW' | 'STOCK_MANAGE' | 'STOCK_DEVICE_LIFECYCLE'
  | 'SHARED_ASSET_VIEW' | 'SHARED_ASSET_MANAGE' | 'NOTIFICATION_VIEW' | 'NOTIFICATION_MANAGE'
  | 'USER_MANAGE' | 'PORTAL_SELF';

const all: UiPermission[] = ['DASHBOARD_VIEW','EMPLOYEE_VIEW','EMPLOYEE_SENSITIVE_VIEW','EMPLOYEE_MANAGE','ROOM_VIEW','ROOM_MANAGE','ROOM_INVENTORY_MANAGE','CLEANING_MANAGE','MAINTENANCE_VIEW','MAINTENANCE_CREATE','MAINTENANCE_UPDATE','MAINTENANCE_FULL_UPDATE','MAINTENANCE_EXPORT','VISITOR_VIEW','VISITOR_MANAGE','VISITOR_ARCHIVE','STOCK_VIEW','STOCK_MANAGE','STOCK_DEVICE_LIFECYCLE','SHARED_ASSET_VIEW','SHARED_ASSET_MANAGE','NOTIFICATION_VIEW','NOTIFICATION_MANAGE','USER_MANAGE','PORTAL_SELF'];

const map: Record<AppRole, ReadonlySet<UiPermission>> = {
  ADMIN: new Set(all), HOUSING_MANAGER: new Set(all),
  HOUSING_STAFF: new Set(['DASHBOARD_VIEW','EMPLOYEE_VIEW','ROOM_VIEW','ROOM_MANAGE','ROOM_INVENTORY_MANAGE','CLEANING_MANAGE','MAINTENANCE_VIEW','MAINTENANCE_CREATE','MAINTENANCE_UPDATE','MAINTENANCE_FULL_UPDATE','MAINTENANCE_EXPORT','VISITOR_VIEW','VISITOR_MANAGE','VISITOR_ARCHIVE','STOCK_VIEW','STOCK_MANAGE','STOCK_DEVICE_LIFECYCLE','SHARED_ASSET_VIEW','SHARED_ASSET_MANAGE','NOTIFICATION_VIEW','NOTIFICATION_MANAGE']),
  TECHNICAL_MANAGER: new Set(['DASHBOARD_VIEW','ROOM_VIEW','ROOM_INVENTORY_MANAGE','MAINTENANCE_VIEW','MAINTENANCE_CREATE','MAINTENANCE_UPDATE','MAINTENANCE_FULL_UPDATE','MAINTENANCE_EXPORT','STOCK_VIEW','STOCK_DEVICE_LIFECYCLE','SHARED_ASSET_VIEW']),
  TECHNICIAN: new Set(['ROOM_VIEW','MAINTENANCE_VIEW','MAINTENANCE_CREATE','MAINTENANCE_UPDATE']),
  HOUSEKEEPING: new Set(['ROOM_VIEW','CLEANING_MANAGE']),
  WAREHOUSE_MANAGER: new Set(['DASHBOARD_VIEW','ROOM_VIEW','STOCK_VIEW','STOCK_MANAGE','STOCK_DEVICE_LIFECYCLE','SHARED_ASSET_VIEW','SHARED_ASSET_MANAGE','MAINTENANCE_VIEW']),
  HR_MANAGER: new Set(['DASHBOARD_VIEW','EMPLOYEE_VIEW','EMPLOYEE_SENSITIVE_VIEW','EMPLOYEE_MANAGE','ROOM_VIEW']),
  SECURITY: new Set(['DASHBOARD_VIEW','ROOM_VIEW','MAINTENANCE_VIEW','MAINTENANCE_CREATE','VISITOR_VIEW','VISITOR_MANAGE']),
  STAFF: new Set(['PORTAL_SELF']),
};

export const isAppRole = (role: string): role is AppRole => (APP_ROLES as readonly string[]).includes(role);
export const can = (role: string, permission: UiPermission) => isAppRole(role) && map[role].has(permission);

export const TAB_PERMISSION: Record<string, UiPermission> = {
  dashboard: 'DASHBOARD_VIEW', employees: 'EMPLOYEE_VIEW', rooms: 'ROOM_VIEW', visitors: 'VISITOR_VIEW',
  issues: 'MAINTENANCE_VIEW', maintenance: 'MAINTENANCE_VIEW', warehouse: 'STOCK_VIEW',
  'shared-assets': 'SHARED_ASSET_VIEW', notifications: 'NOTIFICATION_VIEW', users: 'USER_MANAGE',
};

export const canAccessTab = (role: string, tab: string) => !TAB_PERMISSION[tab] || can(role, TAB_PERMISSION[tab]);
export const firstAllowedTab = (role: string) => ['dashboard','rooms','issues','employees','visitors','warehouse','shared-assets','notifications','users'].find((tab) => canAccessTab(role, tab)) || 'rooms';
